-- DO NOT EDIT THIS FILE AFTER IT IS PUSHED IT WILL DIVERGE THE DATABASE
-- IF YOU WANT TO EDIT THE YOU HAVE TO ADD A SEPARATE V2__add_something.sql file

USE reportingdb;

-- The read model behind the jobs-by-status report. Not a table this service
-- writes from an API: every row here is a copy of a fact the Job Service owns,
-- absorbed from the job-created topic.
--
-- Indexes are declared inline rather than as separate CREATE INDEX statements:
-- MySQL 8 has no CREATE INDEX IF NOT EXISTS, so keeping them inside the table
-- definition is what makes this whole migration safe to re-run.
CREATE TABLE IF NOT EXISTS job_projection (
    -- The Job Service's job id, carried through unchanged. It is the primary
    -- key here rather than a local surrogate, and that choice is what makes the
    -- projection idempotent: Kafka delivers at least once, so the same
    -- JobCreated event can arrive twice, and the second arrival collides with
    -- this key and updates the row instead of inserting a second copy of the
    -- same job. Without it a redelivery would double every count in the report.
    job_id           CHAR(36)    NOT NULL,
    -- The JOB- handle. Carried because a report row a person reads has to name
    -- the job the way an Agent would say it, not by its UUID.
    job_reference    VARCHAR(20) NOT NULL,
    status           VARCHAR(20) NOT NULL,
    region           VARCHAR(50) NOT NULL,
    priority         VARCHAR(20) NOT NULL,
    service_category VARCHAR(50) NOT NULL,
    -- When the job was created in the Job Service - the business timestamp the
    -- report filters on. It is not when this row appeared, which is the next
    -- column; the two differ by however long the event took to arrive.
    job_created_at   TIMESTAMP   NOT NULL,
    -- When this read model absorbed the event. Written by the database rather
    -- than the consumer, and refreshed on every upsert, so a redelivery leaves
    -- a record that the row was seen again.
    projected_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (job_id),
    -- The two columns the report actually runs on: it groups by status and
    -- filters by job_created_at. Neither index is speculative - they are the
    -- report's GROUP BY and its WHERE.
    KEY idx_job_projection_status (status),
    KEY idx_job_projection_job_created_at (job_created_at)

    -- No CHECK constraints on status or region, and that is a deliberate
    -- difference from the jobs table in jobdb, which constrains both.
    --
    -- The jobs table is where those values originate, so it is the right place
    -- to reject a bad one. This table is a projection of that data: by the time
    -- a value reaches here the Job Service has already accepted it and told
    -- everyone about it. A CHECK here could only ever reject a value the owning
    -- service considers valid.
    --
    -- The failure that would cause is worth being concrete about. If Job
    -- Service adds ASSIGNED to the job lifecycle, the first such event arrives
    -- on a topic this consumer is subscribed to. With a CHECK, the insert
    -- fails, the write is retried forever, the offset is never committed, and
    -- the consumer stops making progress on every later event too - one new
    -- enum value upstream halts the whole report. Without it the row lands, the
    -- report grows a row for the new status, and nothing needed a coordinated
    -- release. Absorbing an unrecognised value is the correct behaviour for a
    -- read model; rejecting it is not.
    --
    -- Also no foreign keys, for the reason the jobs table has none: these
    -- columns name rows in jobdb, a different database owned by a different
    -- service, and MySQL cannot constrain across that boundary.
);
